<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="RazorConsole.Core" Version="0.2.2-alpha.20251201-0ed2924" />
      <PackageReference Include="Spectre.Console" Version="0.54.1-alpha.0.7" />
    </ItemGroup>

</Project>
