name: .NET Console App Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    env:
      PROJECT_FILE: StarCitizenCalculator.csproj
      APP_NAME: DeliveryCalculator

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 
      
      - name: Publish (Build EXE)
        run: dotnet publish ${{ env.PROJECT_FILE }} --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true -o release_output
      
      - name: Archive Build Artifact
        run: |
          $tagName = "${{ github.ref_name }}" 
          $zipFileName = "${{ env.APP_NAME }}_${tagName}_Win-x64.zip"
          Compress-Archive -Path .\release_output\* -DestinationPath $zipFileName
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false 
          prerelease: false
          files: ${{ env.APP_NAME }}_${{ github.ref_name }}_Win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}